[theme]
base = "light"
primaryColor = "#0879A5"
backgroundColor = "#F7FBFF"
secondaryBackgroundColor = "#EAF4FB"
textColor = "#173F5C"
font = "sans serif"
borderColor = "#D2E1ED"
showWidgetBorder = true
showSidebarBorder = true

[theme.sidebar]
backgroundColor = "#073556"
secondaryBackgroundColor = "#0A4772"
textColor = "#FFFFFF"

[client]
showSidebarNavigation = false
showErrorDetails = false
showErrorLinks = false
toolbarMode = "minimal"


